import { useState } from "react";
import { AlertTriangle, Check, ChevronDown, Clock3, Download, FileVideo, FolderOpen, MoreHorizontal, Plus, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";

type Preset = { name: string; detail: string; meta: string; tone?: "accent" | "muted" };

const builtIns: Preset[] = [
  { name: "Social MP4", detail: "1080p · 60 fps", meta: "MP4 · 18.4 MB", tone: "accent" },
  { name: "Help Scout", detail: "720p · 30 fps", meta: "MP4 · 8.7 MB" },
  { name: "GIF Preview", detail: "720p · 30 fps", meta: "GIF · 6.2 MB" },
  { name: "Custom", detail: "Manual settings", meta: "MP4 · 18.4 MB", tone: "muted" },
];

function Surface({ children, title = "Export" }: { children: React.ReactNode; title?: string }) {
  return <main className="min-h-full bg-[#111113] p-7 text-slate-200 font-sans"><div className="mx-auto max-w-[650px]">{children}<div className="mt-5 flex items-center gap-2 text-[11px] text-slate-500"><span className="h-1.5 w-1.5 rounded-full bg-[#DA1F26]" /> Existing SettingsPanel export surface · UI concept for STE-1</div></div></main>;
}

function PresetRow({ preset, selected, onClick, onDelete }: { preset: Preset; selected?: boolean; onClick?: () => void; onDelete?: () => void }) {
  return <button onClick={onClick} className={`group flex w-full items-center gap-3 rounded-xl border px-3 py-3 text-left transition ${selected ? "border-[#DA1F26]/70 bg-[#DA1F26]/10" : "border-white/10 bg-white/[0.03] hover:border-white/20"}`}>
    <span className={`flex h-9 w-9 items-center justify-center rounded-lg ${selected ? "bg-[#DA1F26] text-white" : "bg-white/[0.07] text-slate-400"}`}><FileVideo className="h-4 w-4" /></span>
    <span className="min-w-0 flex-1"><span className="block text-sm font-medium">{preset.name}</span><span className="mt-0.5 block text-[11px] text-slate-500">{preset.detail}</span></span>
    <span className="text-right"><span className="block text-[11px] text-slate-400">{preset.meta}</span>{onDelete && <span onClick={(e) => { e.stopPropagation(); onDelete(); }} className="mt-1 inline-flex cursor-pointer items-center gap-1 text-[10px] text-slate-500 opacity-0 transition group-hover:opacity-100 hover:text-red-300"><Trash2 className="h-3 w-3" /> Delete</span>}</span>
  </button>;
}

function Header({ eyebrow = "EXPORT SETTINGS", title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) {
  return <div className="mb-5 flex items-start justify-between"><div><p className="mb-1 text-[10px] font-semibold tracking-[0.18em] text-[#DA1F26]">{eyebrow}</p><h1 className="text-2xl font-semibold tracking-tight text-white">{title}</h1></div>{action}</div>;
}

function PresetCard({ selected = "Custom", open = false, onOpen }: { selected?: string; open?: boolean; onOpen?: () => void }) {
  const current = builtIns.find((p) => p.name === selected) || builtIns[3];
  return <section className="relative rounded-2xl border border-white/10 bg-[#19191c] p-4 shadow-xl"><div className="mb-3 flex items-center justify-between"><div><p className="text-[11px] font-medium text-slate-400">PRESET</p><p className="mt-1 text-base font-semibold text-white">{current.name}</p></div><Button onClick={onOpen} variant="outline" size="sm" className="gap-2 border-white/10 bg-white/[0.04] text-slate-200 hover:bg-white/10">Change <ChevronDown className="h-3.5 w-3.5" /></Button></div><div className="grid grid-cols-3 gap-2 text-[11px]"><div className="rounded-lg bg-white/[0.04] px-3 py-2"><span className="block text-slate-500">Format</span><span className="mt-1 block text-slate-200">{current.meta.split(" · ")[0]}</span></div><div className="rounded-lg bg-white/[0.04] px-3 py-2"><span className="block text-slate-500">Quality</span><span className="mt-1 block text-slate-200">{current.detail}</span></div><div className="rounded-lg bg-white/[0.04] px-3 py-2"><span className="block text-slate-500">Est. size</span><span className="mt-1 block text-slate-200">{current.meta.split(" · ")[1]}</span></div></div>{open && <div className="absolute left-4 right-4 top-[92px] z-10 rounded-xl border border-white/10 bg-[#202023] p-2 shadow-2xl">{builtIns.map((preset) => <div key={preset.name} className="mb-1 last:mb-0"><PresetRow preset={preset} selected={preset.name === selected} /></div>)}<button className="mt-1 flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs text-slate-400 hover:bg-white/5 hover:text-white"><Plus className="h-3.5 w-3.5" /> Save current settings as preset</button></div>}</section>;
}

function Controls({ selected = "Social MP4", warning = false }: { selected?: string; warning?: boolean }) {
  return <section className="mt-4 rounded-2xl border border-white/10 bg-[#19191c] p-4"><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-medium text-white">Output settings</p><p className="mt-1 text-[11px] text-slate-500">{selected} controls are ready to review</p></div><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-300">Ready</span></div><div className="grid grid-cols-2 gap-2">{[["Destination", selected === "Help Scout" ? "Help Scout" : "Custom"],["Resolution", selected === "GIF Preview" ? "720p" : "1080p"],["Frame rate", selected === "GIF Preview" ? "30 fps" : "60 fps"],["Bitrate", selected === "Help Scout" ? "Auto · size aware" : "Auto · high quality"]].map(([label, value]) => <div key={label} className="rounded-lg border border-white/5 bg-white/[0.03] px-3 py-2.5"><span className="block text-[10px] text-slate-500">{label}</span><span className="mt-1 block text-xs text-slate-200">{value}</span></div>)}</div>{warning && <div className="mt-3 flex items-start gap-2 rounded-xl border border-amber-400/20 bg-amber-400/10 p-3 text-xs text-amber-100"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" /><div><p className="font-medium">Estimated size is over the 10 MB Help Scout limit</p><p className="mt-1 text-[11px] text-amber-200/70">Choose a smaller preset or switch to Custom to tune quality manually.</p><div className="mt-2 flex gap-2"><Button size="sm" className="h-7 bg-amber-300 px-2 text-[10px] text-black hover:bg-amber-200">Choose smaller preset</Button><Button size="sm" variant="outline" className="h-7 border-amber-300/20 px-2 text-[10px] text-amber-100">Switch to Custom</Button></div></div></div>}</section>;
}

export function ExportPresetsFirstUse() { return <Surface><Header title="Export your clip" action={<Button className="bg-[#DA1F26] text-white hover:bg-[#DA1F26]/90"><Download className="mr-2 h-4 w-4" /> Export</Button>} /><PresetCard onOpen={() => undefined} /><Controls selected="Custom" /></Surface>; }

export function PresetPickerOpen() { return <Surface><Header title="Export your clip" /><PresetCard open /><div className="mt-4 rounded-xl border border-dashed border-white/10 p-4 text-center text-xs text-slate-500">Choose a preset to populate the controls below</div></Surface>; }

export function PresetApplied() { const [selected, setSelected] = useState("Social MP4"); return <Surface><Header title="Export your clip" action={<Button className="bg-[#DA1F26] text-white hover:bg-[#DA1F26]/90"><Download className="mr-2 h-4 w-4" /> Export</Button>} /><PresetCard selected={selected} onOpen={() => setSelected(selected === "Social MP4" ? "Custom" : "Social MP4")} /><Controls selected={selected} /><button className="mt-3 flex items-center gap-2 text-xs text-slate-400 hover:text-white"><Plus className="h-3.5 w-3.5" /> Save current settings as preset</button></Surface>; }

export function SavePresetDialog() { return <Surface><Header title="Export your clip" /><PresetCard selected="Social MP4" /><div className="mt-4 rounded-2xl border border-white/10 bg-[#202023] p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-base font-semibold text-white">Save as preset</p><p className="mt-1 text-xs text-slate-500">Reuse these export settings next time.</p></div><X className="h-4 w-4 text-slate-500" /></div><label className="mt-5 block text-[11px] font-medium text-slate-300">Preset name</label><input autoFocus defaultValue="Customer demo" className="mt-2 w-full rounded-xl border border-[#DA1F26]/70 bg-black/20 px-3 py-2.5 text-sm text-white outline-none" /><p className="mt-2 text-[11px] text-slate-500">Saved locally on this device</p><div className="mt-5 flex justify-end gap-2"><Button variant="outline" className="border-white/10 text-slate-300">Cancel</Button><Button className="bg-[#DA1F26] text-white hover:bg-[#DA1F26]/90"><Check className="mr-2 h-4 w-4" /> Save preset</Button></div></div></Surface>; }

export function SavedPresetManagement() { const [deleted, setDeleted] = useState(false); return <Surface><Header title="Export your clip" action={<Button variant="outline" className="gap-2 border-white/10 text-slate-300"><MoreHorizontal className="h-4 w-4" /> Manage</Button>} /><PresetCard selected="Customer demo" onOpen={() => undefined} /><Controls selected="Customer demo" /><div className="mt-4 rounded-2xl border border-white/10 bg-[#19191c] p-3"><div className="mb-2 flex items-center justify-between px-1"><p className="text-[11px] font-medium text-slate-400">SAVED PRESETS</p><span className="text-[10px] text-slate-600">{deleted ? 0 : 1} preset</span></div>{deleted ? <p className="rounded-xl border border-dashed border-white/10 p-4 text-center text-xs text-slate-500">No saved presets yet. Save your current settings to add one.</p> : <PresetRow preset={{ name: "Customer demo", detail: "1080p · 60 fps", meta: "MP4 · 18.4 MB" }} selected onDelete={() => setDeleted(true)} />}</div></Surface>; }

export function LimitWarning() { return <Surface><Header title="Keep it under the limit" /><PresetCard selected="Help Scout" /><Controls selected="Help Scout" warning /><div className="mt-4 flex items-center gap-2 text-[11px] text-slate-500"><FolderOpen className="h-3.5 w-3.5" /> Help Scout limit · 10 MB · estimated output 12.8 MB</div></Surface>; }

export function ExportInProgress() { return <Surface><Header eyebrow="EXPORTING · SOCIAL MP4" title="Your clip is rendering" /><div className="rounded-2xl border border-white/10 bg-[#19191c] p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#DA1F26]/15"><Clock3 className="h-5 w-5 animate-pulse text-[#DA1F26]" /></div><div><p className="text-sm font-medium text-white">Exporting with Social MP4</p><p className="mt-1 text-xs text-slate-500">1080p · 60 fps · MP4</p></div></div><div className="mt-6 flex items-center justify-between text-xs"><span className="text-slate-400">Rendering frames</span><span className="font-mono text-white">68%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[68%] rounded-full bg-[#DA1F26]" /></div><p className="mt-3 text-[11px] text-slate-500">About 24 seconds remaining · Finish at 2:18 PM</p><Button variant="outline" className="mt-5 border-white/10 text-slate-300">Cancel export</Button></div></Surface>; }

export function ExportError() { return <Surface><Header eyebrow="EXPORT FAILED" title="We couldn’t finish that export" /><div className="rounded-2xl border border-red-400/20 bg-red-400/5 p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-red-400/10"><X className="h-5 w-5 text-red-300" /></div><div><p className="text-sm font-medium text-white">Export interrupted</p><p className="mt-1 text-xs text-slate-400">Your original clip is unchanged.</p></div></div><p className="mt-5 rounded-xl bg-black/20 p-3 text-xs leading-relaxed text-slate-400">The renderer stopped before the file could be finalized. Check your export settings and try again.</p><div className="mt-5 flex gap-2"><Button className="bg-[#DA1F26] text-white hover:bg-[#DA1F26]/90">Try again</Button><Button variant="outline" className="border-white/10 text-slate-300">Back to settings</Button></div></div></Surface>; }
